### ISSUE TITLE
error building file help

### ISSUE THREAD

**Issue by Aboda7m** [mifanbang/Herbicide#1]
Severity	Code	Description	Project	File	Line	Suppression State
Error	C1083	Cannot open include file: 'payload.h': No such file or directory	launcher	d:\app building test\herbicide-master\herbicide\launcher\launcher.cpp	30

**Comment by mifanbang** [comment]
Thanks for reporting. Commit 85830a4 should resolve the build issue. That said, the latest version of the game seems to hard-embed the censorship into all CGs, which means **this tool is no longer working** as it doesn't modify game assets.
